-- Add support for expenses paid from accounts/cash.
-- Safe migration: it does not delete existing data.
-- Run this once in Supabase SQL Editor before enabling cash/account expenses in the app.

-- public.expenses.credit_card_id keeps representing credit card expenses.
-- public.expenses.account_id represents expenses paid from an account, including cash wallets.
alter table public.expenses
add column if not exists account_id uuid;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'expenses_account_id_fkey'
      and conrelid = 'public.expenses'::regclass
  ) then
    alter table public.expenses
    add constraint expenses_account_id_fkey
    foreign key (account_id)
    references public.accounts(id)
    on delete restrict;
  end if;
end;
$$;

-- Existing card expenses remain valid because they already have credit_card_id.
-- New account/cash expenses need credit_card_id to be nullable.
alter table public.expenses
alter column credit_card_id drop not null;

-- Each expense must have exactly one payment source:
-- either a credit card or an account/cash wallet, never both and never neither.
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'expenses_single_payment_source_check'
      and conrelid = 'public.expenses'::regclass
  ) then
    alter table public.expenses
    add constraint expenses_single_payment_source_check
    check (
      (credit_card_id is not null and account_id is null)
      or
      (credit_card_id is null and account_id is not null)
    );
  end if;
end;
$$;

comment on column public.expenses.credit_card_id is
'Payment source for credit card expenses. Must be null when the expense was paid from an account or cash wallet.';

comment on column public.expenses.account_id is
'Payment source for expenses paid from an account, including cash wallets. Must be null when the expense was paid with a credit card.';

-- public.account_movements.expense_id links the automatic account movement
-- generated by an account/cash expense.
alter table public.account_movements
add column if not exists expense_id uuid;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'account_movements_expense_id_fkey'
      and conrelid = 'public.account_movements'::regclass
  ) then
    alter table public.account_movements
    add constraint account_movements_expense_id_fkey
    foreign key (expense_id)
    references public.expenses(id)
    on delete cascade;
  end if;
end;
$$;

comment on column public.account_movements.expense_id is
'Links an automatic account movement to the account/cash expense that created it.';

create index if not exists expenses_account_id_idx
on public.expenses(account_id);

-- One account/cash expense should create at most one automatic account movement.
create unique index if not exists account_movements_expense_id_unique_idx
on public.account_movements(expense_id)
where expense_id is not null;

-- Keep RLS enabled on the affected user-owned tables.
-- Existing policies are expected to keep using auth.uid() = user_id.
alter table public.expenses enable row level security;
alter table public.account_movements enable row level security;

-- Verification queries.
-- These queries do not modify data; they only help confirm the migration.
select
  table_name,
  column_name,
  data_type,
  is_nullable
from information_schema.columns
where table_schema = 'public'
  and (
    (table_name = 'expenses' and column_name in ('credit_card_id', 'account_id'))
    or
    (table_name = 'account_movements' and column_name = 'expense_id')
  )
order by table_name, column_name;

select
  conrelid::regclass as table_name,
  conname,
  contype,
  pg_get_constraintdef(oid) as definition
from pg_constraint
where conrelid in ('public.expenses'::regclass, 'public.account_movements'::regclass)
  and conname in (
    'expenses_account_id_fkey',
    'expenses_single_payment_source_check',
    'account_movements_expense_id_fkey'
  )
order by table_name, conname;

select
  tablename,
  indexname,
  indexdef
from pg_indexes
where schemaname = 'public'
  and (
    (tablename = 'expenses' and indexname = 'expenses_account_id_idx')
    or
    (tablename = 'account_movements' and indexname = 'account_movements_expense_id_unique_idx')
  )
order by tablename, indexname;

select
  tablename,
  rowsecurity
from pg_tables
where schemaname = 'public'
  and tablename in ('expenses', 'account_movements')
order by tablename;
